"""Tables for the paper: CSV for the data, LaTeX for the manuscript.

Both formats come from one list-of-dicts so they cannot disagree. The CSV is the
artefact a reader can check; the LaTeX is a convenience for typesetting and is
deliberately plain — `booktabs` rules, no colour, no vertical lines, so it works
in a printed monochrome proceedings.

Numbers are written at the precision they were computed at. Rounding for display
happens in the LaTeX only, never in the CSV, so nothing is lost between the
database and the archive.
"""

from __future__ import annotations

import csv
import logging
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from ..db import Conn, fetch_all

log = logging.getLogger(__name__)

# LaTeX's ten special characters. A commodity name with an ampersand in it
# should not silently produce an unbuildable manuscript.
LATEX_ESCAPES = {
    "\\": r"\textbackslash{}",
    "&": r"\&",
    "%": r"\%",
    "$": r"\$",
    "#": r"\#",
    "_": r"\_",
    "{": r"\{",
    "}": r"\}",
    "~": r"\textasciitilde{}",
    "^": r"\textasciicircum{}",
}


@dataclass
class Table:
    slug: str
    caption: str
    rows: list[dict[str, Any]]
    note: str = ""

    @property
    def columns(self) -> list[str]:
        return list(self.rows[0]) if self.rows else []


def _latex_escape(value: Any) -> str:
    if value is None:
        return "--"
    text = str(value)
    return "".join(LATEX_ESCAPES.get(ch, ch) for ch in text)


def _format_cell(value: Any) -> str:
    if isinstance(value, float):
        return f"{value:.4f}"
    return _latex_escape(value)


def write_csv(table: Table, directory: Path) -> Path:
    path = directory / f"{table.slug}.csv"
    with path.open("w", newline="", encoding="utf-8") as handle:
        if not table.rows:
            handle.write("")
            return path
        writer = csv.DictWriter(handle, fieldnames=table.columns)
        writer.writeheader()
        writer.writerows(table.rows)
    return path


def write_latex(table: Table, directory: Path) -> Path:
    path = directory / f"{table.slug}.tex"
    if not table.rows:
        path.write_text(
            f"% {table.slug}: no rows.\n% {table.note}\n",
            encoding="utf-8",
        )
        return path

    columns = table.columns
    # Numeric columns right-aligned, everything else left. Guessing from the
    # first row is enough here and beats hand-maintaining a spec per table.
    alignment = "".join("r" if isinstance(table.rows[0][c], (int, float)) else "l" for c in columns)

    lines = [
        "% Generated by `siap export`. Do not edit; regenerate.",
        r"\begin{table}[htbp]",
        r"  \centering",
        f"  \\caption{{{_latex_escape(table.caption)}}}",
        f"  \\label{{tab:{table.slug.replace('_', '-')}}}",
        f"  \\begin{{tabular}}{{{alignment}}}",
        r"    \toprule",
        "    " + " & ".join(_latex_escape(c.replace("_", " ")) for c in columns) + r" \\",
        r"    \midrule",
    ]
    for row in table.rows:
        lines.append("    " + " & ".join(_format_cell(row[c]) for c in columns) + r" \\")
    lines += [r"    \bottomrule", r"  \end{tabular}"]
    if table.note:
        lines.append(f"  \\par\\smallskip\\footnotesize {_latex_escape(table.note)}")
    lines += [r"\end{table}", ""]

    path.write_text("\n".join(lines), encoding="utf-8")
    return path


# ---------------------------------------------------------------------------
# The tables themselves
# ---------------------------------------------------------------------------
def commodities_table(conn: Conn) -> Table:
    return Table(
        slug="tab_commodities",
        caption="Commodities tracked, with canonical units and plausibility bands.",
        rows=fetch_all(
            conn,
            """
            select c.slug, c.display_name, c.canonical_unit,
                   c.price_min_plausible::bigint as plausible_min,
                   c.price_max_plausible::bigint as plausible_max
              from public.commodities c
             order by c.sort_order
            """,
        ),
        note=(
            "The plausibility band rejects unit and parsing errors before analysis; "
            "a rejected observation is recorded, never silently dropped."
        ),
    )


def sources_table(conn: Conn) -> Table:
    return Table(
        slug="tab_sources",
        caption="Data sources, their cadence and the observations collected from each.",
        rows=fetch_all(
            conn,
            """
            select s.slug, s.cadence, s.is_active,
                   count(o.id) as observations,
                   min(o.obs_date) as first_date,
                   max(o.obs_date) as last_date
              from public.sources s
              left join public.price_observations o on o.source_id = s.id
             group by s.id, s.slug, s.cadence, s.is_active
             order by s.slug
            """,
        ),
        note=(
            "An inactive source is one whose portal is broken upstream; its absence is "
            "recorded in fetch_failures rather than filled in."
        ),
    )


def coverage_table(conn: Conn) -> Table:
    return Table(
        slug="tab_coverage",
        caption="Unified daily series: coverage and imputation per region.",
        rows=fetch_all(
            conn,
            """
            select rg.slug as region,
                   count(*) as series_days,
                   count(*) filter (where u.price_median is not null) as with_price,
                   count(*) filter (where u.is_imputed) as imputed,
                   round(avg(u.n_sources)::numeric, 3) as mean_sources,
                   min(u.obs_date) as first_date,
                   max(u.obs_date) as last_date
              from public.price_daily_unified u
              join public.regions rg on rg.id = u.region_id
             group by rg.slug, rg.level
             order by case rg.level
                        when 'national' then 0 when 'province' then 1 else 2
                      end, rg.slug
            """,
        ),
        note=(
            "Imputed days are interpolated across gaps of at most three days and are "
            "excluded from every model input; the column is reported so the reader can "
            "see how much of the series is not observation."
        ),
    )


def flag_counts_table(conn: Conn, anomaly_run_id: int) -> Table:
    return Table(
        slug="tab_flag_counts",
        caption="Days flagged by each detector, and their overlap.",
        rows=fetch_all(
            conn,
            """
            with f as (
              select method, commodity_id, region_id, obs_date
                from public.anomaly_scores
               where run_id = %s and is_flagged
            )
            select method,
                   count(*) as flagged,
                   count(*) filter (where exists (
                       select 1 from f o
                        where o.method <> f.method
                          and o.commodity_id = f.commodity_id
                          and o.region_id    = f.region_id
                          and o.obs_date     = f.obs_date)) as also_flagged_by_the_other
              from f
             group by method
             order by method
            """,
            (anomaly_run_id,),
        ),
        note=(
            "Low overlap is the premise of the hybrid: two detectors that agreed on "
            "everything would make the fusion step pointless."
        ),
    )


def k_search_table(rows: list[dict[str, Any]]) -> Table:
    # Computed, not written down: the margin moves with the data, and a note that
    # hardcodes it goes stale without anything failing. That is exactly how this
    # table came to carry an editorial constraint two milestones after its removal.
    selected = next((r for r in rows if r["selected"]), None)
    runner_up = max(
        (r for r in rows if not r["selected"]), key=lambda r: r["silhouette"], default=None
    )
    if selected is None or runner_up is None:
        note = "Every k in the search range is fitted, scored and reported."
    else:
        note = (
            f"k={selected['k']} is selected on silhouette alone, ahead of k={runner_up['k']} "
            f"by {selected['silhouette'] - runner_up['silhouette']:.4f}. The three-zone floor "
            f"that once excluded k=2 was removed in M10; every k in the range is fitted, "
            f"scored and reported, and the highest score wins."
        )
    return Table(
        slug="tab_k_search",
        caption="K-Means model selection: silhouette and inertia across the search range.",
        rows=rows,
        note=note,
    )


def contamination_table(rows: list[dict[str, Any]], note: str) -> Table:
    return Table(
        slug="tab_contamination",
        caption="IsolationForest contamination: flag volume and set overlap.",
        rows=rows,
        note=note,
    )


def weight_sensitivity_table(rows: list[dict[str, Any]], note: str) -> Table:
    return Table(
        slug="tab_weight_sensitivity",
        caption="Fusion weight perturbation: ranking stability and alert level counts.",
        rows=rows,
        note=note,
    )


def zone_counts_table(conn: Conn, cluster_run_id: int) -> Table:
    return Table(
        slug="tab_zone_counts",
        caption="Regime zone assignment per commodity, over all months.",
        rows=fetch_all(
            conn,
            """
            select c.slug as commodity,
                   count(*) filter (where a.zone = 'merah')  as merah,
                   count(*) filter (where a.zone = 'kuning') as kuning,
                   count(*) filter (where a.zone = 'hijau')  as hijau,
                   count(*) filter (where a.zone is null)    as gated,
                   count(*) as months,
                   round(avg(a.feat_volatility) filter (where a.zone is not null)::numeric, 5)
                       as mean_volatility
              from public.cluster_assignments a
              join public.commodities c on c.id = a.commodity_id
             where a.run_id = %s
             group by c.slug, c.sort_order
             order by c.sort_order
            """,
            (cluster_run_id,),
        ),
        note=(
            "Zones describe how a price has behaved, not where it will go next. "
            "`gated` counts months excluded from the fit on data provenance; they are "
            "kept in the table so this column is reportable, and are omitted from "
            "mean_volatility because their volatility measures a publication cadence."
        ),
    )


def write_all(tables: list[Table], directory: Path) -> list[Path]:
    directory.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    for table in tables:
        written.append(write_csv(table, directory))
        written.append(write_latex(table, directory))
    return written
