"""Filesystem anchors.

Every path in the engine is resolved from the repository root rather than from
the current working directory, so `siap migrate` behaves identically whether it
is run from `engine/`, from the repo root, or from a GitHub Actions step.
"""

from __future__ import annotations

from functools import lru_cache
from pathlib import Path

# A directory is the repo root when it contains all of these.
_ROOT_MARKERS = ("supabase/migrations", "engine/config", ".gitignore")


class RepoRootNotFound(RuntimeError):
    """Raised when the repository layout cannot be located from this module."""


@lru_cache(maxsize=1)
def repo_root() -> Path:
    """Walk upwards from this file until the repository layout is recognised."""
    here = Path(__file__).resolve()
    for candidate in (here, *here.parents):
        if all((candidate / marker).exists() for marker in _ROOT_MARKERS):
            return candidate
    raise RepoRootNotFound(
        f"Could not locate the SIAP-PANGAN repository root above {here}. "
        f"Expected a directory containing: {', '.join(_ROOT_MARKERS)}."
    )


def config_dir() -> Path:
    """`engine/config/` — YAML reference data and analysis parameters."""
    return repo_root() / "engine" / "config"


def migrations_dir() -> Path:
    """`supabase/migrations/` — numbered SQL migrations, the schema source of truth."""
    return repo_root() / "supabase" / "migrations"


def docs_dir() -> Path:
    """`docs/` — architecture, sources, methods, reproducibility, changelog."""
    return repo_root() / "docs"


def paper_exports_dir() -> Path:
    """`paper-exports/` — generated figures and tables. Gitignored; regenerated by `make paper`."""
    return repo_root() / "paper-exports"
