import type { Metadata, Viewport } from "next";
import "./globals.css";

// Typography is deliberately left as the system stack for now. The display /
// body / mono pairing is a design decision that belongs in docs/design.md and
// is made in M8 — picking a webfont here would prejudge it, and would add a
// build-time network fetch for no benefit.

const DESCRIPTION =
  "Pantau harga bahan pangan dari sumber resmi. Tahu bahan mana yang sedang naik tidak wajar.";

export const metadata: Metadata = {
  title: "SIAP-PANGAN",
  description: DESCRIPTION,
  // The link gets shared in WhatsApp, so the card matters. The image itself is
  // generated by app/opengraph-image.tsx and picked up automatically; these fields
  // are what turn a bare URL into something with a name and a language.
  openGraph: {
    type: "website",
    locale: "id_ID",
    siteName: "SIAP-PANGAN",
    title: "SIAP-PANGAN",
    description: DESCRIPTION,
  },
  twitter: { card: "summary_large_image" },
};

// Mobile-first: a warung owner opens this on a phone, one-handed.
export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  // Matches the manifest and the dark background, so the phone's browser chrome
  // stops flashing white before the page paints on a slow connection.
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#ffffff" },
    { media: "(prefers-color-scheme: dark)", color: "#0a0a0a" },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="id">
      <body className="antialiased">{children}</body>
    </html>
  );
}
