import type { Metadata, Viewport } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";

/**
 * Plus Jakarta Sans, self-hosted.
 *
 * design.md ruled out a webfont because it meant a render-blocking request to a
 * third party on a slow connection. `next/font` removes that objection rather
 * than ignoring it: the file is fetched at build time and served from this
 * origin, preloaded, with no runtime connection to Google at all. `display:
 * swap` means text paints in the system stack immediately and reflows when the
 * face arrives, so a failed or slow font costs legibility nothing.
 *
 * The face is commissioned Indonesian type, which is a reason to prefer it over
 * the usual product-sans defaults for this subject in particular.
 */
const jakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-jakarta",
});

const DESCRIPTION =
  "Pantau harga bahan pangan dari sumber resmi. Tahu bahan mana yang sedang naik tidak wajar.";

export const metadata: Metadata = {
  title: "SIAP-PANGAN",
  description: DESCRIPTION,
  // The link gets shared in WhatsApp, so the card matters. The image itself is
  // generated by app/opengraph-image.tsx and picked up automatically; these fields
  // are what turn a bare URL into something with a name and a language.
  openGraph: {
    type: "website",
    locale: "id_ID",
    siteName: "SIAP-PANGAN",
    title: "SIAP-PANGAN",
    description: DESCRIPTION,
  },
  twitter: { card: "summary_large_image" },
};

// Mobile-first: a warung owner opens this on a phone, one-handed.
export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  // Matches the manifest and the dark background, so the phone's browser chrome
  // stops flashing white before the page paints on a slow connection.
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#f7f8f6" },
    { media: "(prefers-color-scheme: dark)", color: "#0a0e0c" },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="id" className={jakarta.variable}>
      <body className="antialiased">{children}</body>
    </html>
  );
}
